### ISSUE TITLE
Global pointer assignment doesn't work

### ISSUE THREAD

**Issue by hd-COO7** [maximecb/uvm#11] opened 2023-03-01 13:59 UTC
A pointer defined globally is not getting assigned value later in code
Code to reproduce
```
char* dummy;
void main()
{
    char* hello = "Hello String";
    puts(hello); //works
    char* test = hello;
    puts(test); //works
    dummy = test;
    puts(dummy); //doesn't works prints 0
}
```

**Comment by maximecb** [comment] 2023-03-01 22:12
I did find this bug before 😅 

I'll get around to fixing it for sure, but lots of work to do on NCC. The compiler is fairly MacGuyvered together 😅 

If you'd like to help fix it, your help is welcome.

**Comment by hd-COO7** [comment] 2023-03-02 05:28
Sure. I'll try to fix this. Can you point in the right direction where to start off ?

**Comment by maximecb** [comment] 2023-03-02 06:27
Sure.

One way to debug this is to look at the instructions output by the compiler. It gets written into the `out.asm` file. It's a human-readable test file. This will be easier to debug if you strip it down to the smallest possible test case:

```
#include <stdio.h>
char* dummy;
void main()
{
    char* hello = "Hello String";
    dummy = hello;
    puts(dummy); //doesn't works prints 0
}
```

So the output code for the main function is:
```
main:
push 0;
push __CONST_STR_0__;
set_local 0;
push dummy;
get_local 0;
store_u64;
push dummy;
call puts, 1;
pop;
push 0;
ret;
```

Here `dummy` is just a label, an address in the heap. At the top of the file we see:

```
dummy:
.u64 0;
```

That's good. It's a 64-bit value (a pointer), and it's initialized to zero (null).

I think the problem is it's pushing the address of the global variable dummy, because it expects the data for the `char*` pointer to directly live at that address... But that's not right, because dummy is not a global array of characters, it's a pointer to a string. We're missing a `load_u64` instruction to load from that pointer and get the actual string data.

**Comment by maximecb** [comment] 2023-03-19 21:26
Should be fixed now.

**Closed by maximecb** 2023-03-19 21:26 UTC
Labels: bug
