### ISSUE TITLE
"undeclared identifier" that doesn't appear in the source code.

### ISSUE THREAD

**Issue by calroc** [maximecb/uvm#17] opened 2023-03-10 18:31 UTC
When compiling `d.c`:

``` C
#include <uvm/graphics.h>

u32
HSVA_to_RGBA(u8 hue, u8 saturation, u8 value, u8 alpha)
{
    u8 chroma = 1;
    u8 m = 1;
    u8 X = 23;
    return rgba32(chroma, m, X, alpha);
}
```

The compiler generates an error message for an undeclared identifier that doesn't appear in the source:

```
uvm/ncc % cargo run ./examples/d.c
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/ncc ./examples/d.c`
Error: reference to undeclared identifier "chromalpha"
```

That's the smallest repro yet, but I haven't tried that hard (yet), e.g. the exact values of the variables don't seem to matter.  (I'm in the middle of making breakfast, but I wanted to give you what I had so far. I'll fiddle with it later today (if you haven't already fixed it! :) )

**Comment by maximecb** [comment] 2023-03-10 19:51
I found a smaller regression:

```
#define rgba32(b, a) (b | a)

int regress(int chroma, int alpha)
{
    return rgba32(alpha, chroma);
}
```

Also confirmed that this works in gcc, but not NCC. The problem seems to be that my preprocessor replaces the tokens one at a time, whereas gcc replaces them all at once.

I should be able to fix this today or tomorrow :)

**Comment by calroc** [comment] 2023-03-10 20:02
Ah, you beat me to it!  Cheers! :)

**Comment by maximecb** [comment] 2023-03-11 05:05
Should be all fixed now :)

**Closed by maximecb** 2023-03-11 05:05 UTC
Labels: bug
